/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_joseluispereira;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author j0c3lwiz
 */
public class princi extends javax.swing.JFrame {

    /**
     * Creates new form princi
     */
    public princi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_borrar = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Ascensos = new javax.swing.JMenuItem();
        crear_gernete = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gg_puesto = new javax.swing.JComboBox<>();
        gg_salario = new javax.swing.JTextField();
        gg_contra = new javax.swing.JTextField();
        gg_id = new javax.swing.JTextField();
        gg_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        gg_empresa = new javax.swing.JTextField();
        mensaje = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        cb_para = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_de = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_texto = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        cb_manuelbb = new javax.swing.JComboBox<>();
        tf_para2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_de2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_gg = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        bt_pieza = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_empleados = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gg_nombre2 = new javax.swing.JTextField();
        gg_contra2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gg_salario2 = new javax.swing.JTextField();
        gg_id2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wombo_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        gg_empresa2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ensa = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popup_borrar.add(Eliminar);

        Ascensos.setText("jMenuItem1");
        Ascensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AscensosActionPerformed(evt);
            }
        });
        popup_borrar.add(Ascensos);

        jButton4.setText("Registar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        jLabel13.setText("ID");

        jLabel14.setText("Contraseña");

        jLabel15.setText("Salario");

        jLabel16.setText("Puesto");

        gg_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente General", " " }));

        gg_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gg_contraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Gerente General");

        jLabel17.setText("Empresa");

        javax.swing.GroupLayout crear_gerneteLayout = new javax.swing.GroupLayout(crear_gernete.getContentPane());
        crear_gernete.getContentPane().setLayout(crear_gerneteLayout);
        crear_gerneteLayout.setHorizontalGroup(
            crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_gerneteLayout.createSequentialGroup()
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_gerneteLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton4))
                    .addGroup(crear_gerneteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crear_gerneteLayout.createSequentialGroup()
                                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gg_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gg_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gg_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(crear_gerneteLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(gg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crear_gerneteLayout.createSequentialGroup()
                                    .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addGap(25, 25, 25)
                                    .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gg_id)
                                        .addComponent(gg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(crear_gerneteLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        crear_gerneteLayout.setVerticalGroup(
            crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_gerneteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(gg_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gg_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(gg_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_gerneteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gg_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jButton5.setText("Enviar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel23.setText("Para:");

        jLabel22.setText("De:");

        jLabel21.setText("Enviar Mensaje Punta a Punta");

        ta_texto.setColumns(20);
        ta_texto.setRows(5);
        jScrollPane5.setViewportView(ta_texto);

        jLabel28.setText("Mensaje");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel21))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel22))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_para, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cb_de, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton5)))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addComponent(cb_de, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Escribir", jPanel5);

        jLabel24.setText("Persona");

        cb_manuelbb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_manuelbbItemStateChanged(evt);
            }
        });

        jLabel25.setText("Para:");

        jLabel26.setText("De:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel27.setText("Mensaje");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel24))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cb_manuelbb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_para2)
                                    .addComponent(tf_de2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                            .addComponent(jLabel27)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_manuelbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_para2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_de2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Leer", jPanel6);

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje.getContentPane());
        mensaje.getContentPane().setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Crear Gerente General");

        bt_gg.setText("Crear gerente general");
        bt_gg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ggMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_gg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(842, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(bt_gg)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 27, 1050, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_arbol);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 59, 274, 256));

        bt_pieza.setText("Enviar al baul");
        bt_pieza.setEnabled(false);
        bt_pieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_piezaMouseClicked(evt);
            }
        });
        jPanel4.add(bt_pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 121, -1));

        jl_empleados.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_empleados);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 281, 256));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Baul de piezas");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jButton1.setText("Enviar a jefe...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 139, -1));

        jLabel8.setText("Click derecho para opciones de empleados");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        jLabel4.setText("Nombre");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setText("Crear Empleados");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        gg_nombre2.setEnabled(false);
        jPanel4.add(gg_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));

        gg_contra2.setEnabled(false);
        gg_contra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gg_contra2ActionPerformed(evt);
            }
        });
        jPanel4.add(gg_contra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        jLabel5.setText("ID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setText("Contraseña");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        gg_salario2.setEnabled(false);
        gg_salario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gg_salario2ActionPerformed(evt);
            }
        });
        jPanel4.add(gg_salario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, -1));

        gg_id2.setEnabled(false);
        jPanel4.add(gg_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, -1));

        jLabel10.setText("Salario");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setText("Puesto");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        wombo_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente de Area", "Empleado de Primera", " " }));
        wombo_combo.setEnabled(false);
        jPanel4.add(wombo_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel2.setText("Empresa");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        gg_empresa2.setEnabled(false);
        jPanel4.add(gg_empresa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        jLabel18.setText("Que es?");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel19.setText("Que es?");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jButton2.setText("Enviar mensaje");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 130, -1));

        jLabel20.setText("Como se usa?");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 173, 1050, 390));

        jTabbedPane1.addTab("Creacion de partes", jPanel1);

        jt_ensa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro", "Pieza", "Tiempo"
            }
        ));
        jScrollPane2.setViewportView(jt_ensa);

        jButton3.setText("Comenzar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jButton3)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ensamblaje", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ggMouseClicked
        // TODO add your handling code here:
        crear_gernete.setModal(true);//para solo poder a acceder a una ventana
        crear_gernete.pack();
        crear_gernete.setLocationRelativeTo(this);//centra con el frame principal
        crear_gernete.setVisible(true);
    }//GEN-LAST:event_bt_ggMouseClicked

    private void bt_piezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_piezaMouseClicked
        // String nombre, String empresa, String contra, String boss, double salario, String puesto
        double Salario = Double.parseDouble(gg_salario.getText());
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        modelo.addElement(new empleados(gg_nombre2.getText(), gg_empresa2.getText(), gg_contra2.getText(), null, Salario, wombo_combo.getSelectedItem().toString()));
        o.add(new empleados(gg_nombre2.getText(), gg_empresa2.getText(), gg_contra2.getText(), null, Salario, wombo_combo.getSelectedItem().toString()));
        cb_de.addItem(gg_nombre2.getText());
        cb_para.addItem(gg_nombre2.getText());

    }//GEN-LAST:event_bt_piezaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //String nombre, String empresa, String contra, String boss, double salario, String puesto
        if (jl_empleados.getSelectedIndex() >= 0) {// verificar si teiene una persona seleccionada
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_arbol.getModel();
            raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtenera la persona a guardar
            DefaultListModel modeloLISTA = (DefaultListModel) jl_empleados.getModel();
            String nombre,empresa,contra,boss,puesto;
            nombre = ((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getNombre();
            empresa=((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getEmpresa();
            contra=((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getContra();
            boss=((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getBoss();
            double salario=((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getSalario();
            puesto=((empleados) modeloLISTA.get(jl_empleados.getSelectedIndex())).getPuesto();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(wombo_combo.getSelectedItem().toString())) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(
                                 new empleados(gg_nombre2.getText(), gg_empresa2.getText(), gg_contra2.getText(), null, salario, wombo_combo.getSelectedItem().toString()));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                }
               
            } if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(wombo_combo.getSelectedItem().toString());
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new empleados(gg_nombre2.getText(), gg_empresa2.getText(), gg_contra2.getText(), null, salario, wombo_combo.getSelectedItem().toString()));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay piezas seleccionadas");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_arbol.setSelectionRow(row);
            Object v1 = jt_arbol.getSelectionPath().getPathComponent(row);
            nodo_pieza = (DefaultMutableTreeNode) v1;
            if (nodo_pieza.getUserObject() instanceof empleados) {
                pieza_selccionada = (empleados) nodo_pieza.getUserObject();
                popup_borrar.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
        
    }//GEN-LAST:event_jt_arbolMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro de Eliminar ? ", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
            m.removeNodeFromParent(nodo_pieza);
            m.reload();
            
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked


    }//GEN-LAST:event_jButton3MouseClicked

    private void gg_salario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gg_salario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gg_salario2ActionPerformed

    private void gg_contra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gg_contra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gg_contra2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        //String nombre, String empresa, String contra, String boss, double salario, String puesto
        if(bt_gg.isEnabled()){
        double Salario = Double.parseDouble(gg_salario.getText());
        empleados temp = new empleados(gg_nombre.getText(), gg_empresa.getText(), gg_contra.getText(), "nadie", Salario, "Gerente General");
        emple.add(temp);
        DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
        raiz = (DefaultMutableTreeNode) m.getRoot();
        nodo_carro = new DefaultMutableTreeNode(
                new empleados(gg_nombre.getText(), gg_empresa.getText(), gg_contra.getText(), "nadie", Salario, "Gerente General"));
        m.setRoot(nodo_carro);
        m.reload();
        bt_gg.setEnabled(false);
        crear_gernete.dispose();
        gg_nombre2.setEnabled(true); 
        gg_empresa2.setEnabled(true); gg_contra2.setEnabled(true); wombo_combo.setEnabled(true);gg_salario2.setEnabled(true);bt_pieza.setEnabled(true);gg_id2.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Recuerda que luego de creado el gerente general no podras crear otro");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void gg_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gg_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gg_contraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Con este boton envias a una jlist para una vista previa del empleado");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
         JOptionPane.showMessageDialog(this, "Con este boton envias un empleado a un jefe");
    }//GEN-LAST:event_jLabel19MouseClicked

    private void AscensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AscensosActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro de Ascender ? ", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
            
            m.reload();
            
        }
    }//GEN-LAST:event_AscensosActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:      
        mensaje.setModal(true);//para solo poder a acceder a una ventana
        mensaje.pack();
        mensaje.setLocationRelativeTo(this);//centra con el frame principal
        mensaje.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void cb_manuelbbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_manuelbbItemStateChanged
        // TODO add your handling code here:
        temp = (mensajes) cb_manuelbb.getSelectedItem();
        if (temp != null) {
            tf_de2.setText(temp.getDestino());
            tf_para2.setText(temp.getFuente());
            ta_texto.setText(temp.getTexto());
            pos = cb_manuelbb.getSelectedIndex();
        }
    }//GEN-LAST:event_cb_manuelbbItemStateChanged

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:administrador ap = new administrador("./mensajes.jlp");
        mensajes m = new mensajes(cb_para.getSelectedItem().toString(),cb_de.getSelectedItem().toString(),ta_texto.getText());
        administrador ap = new administrador("./mensajes.jlp");
        ap.cargarArchivo();
        ap.setPersona(m);
        ap.escribir();
        JOptionPane.showMessageDialog(this, "Mensaje enviado exitosamente");

        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        if (jTabbedPane2.getSelectedIndex() == 1) {           
            administrador ap = new administrador("./mensajes.jlp");
            ap.cargarArchivo();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListapersonas().toArray());
            System.out.println("entra"+ap.getListapersonas());
            cb_manuelbb.setModel(modelo);
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new princi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ascensos;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JButton bt_gg;
    private javax.swing.JButton bt_pieza;
    private javax.swing.JComboBox<String> cb_de;
    private javax.swing.JComboBox<String> cb_manuelbb;
    private javax.swing.JComboBox<String> cb_para;
    private javax.swing.JDialog crear_gernete;
    private javax.swing.JTextField gg_contra;
    private javax.swing.JTextField gg_contra2;
    private javax.swing.JTextField gg_empresa;
    private javax.swing.JTextField gg_empresa2;
    private javax.swing.JTextField gg_id;
    private javax.swing.JTextField gg_id2;
    private javax.swing.JTextField gg_nombre;
    private javax.swing.JTextField gg_nombre2;
    private javax.swing.JComboBox<String> gg_puesto;
    private javax.swing.JTextField gg_salario;
    private javax.swing.JTextField gg_salario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> jl_empleados;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTable jt_ensa;
    private javax.swing.JDialog mensaje;
    private javax.swing.JPopupMenu popup_borrar;
    private javax.swing.JTextArea ta_texto;
    private javax.swing.JTextField tf_de2;
    private javax.swing.JTextField tf_para2;
    private javax.swing.JComboBox<String> wombo_combo;
    // End of variables declaration//GEN-END:variables
DefaultMutableTreeNode nodo_carro;
    DefaultMutableTreeNode nodo_pieza;
    DefaultListModel model;
    ArrayList o = new ArrayList();
    ArrayList o2 = new ArrayList();
    ArrayList<empleados> emple = new ArrayList();
    int aux = 0;
    empleados pieza_selccionada;
    DefaultMutableTreeNode raiz;
    mensajes temp;
    int pos;
}
